Handle return data larger than a word
FuelLabs/fuels-rs pull request #112
Opened 2022-02-24 22:57 UTC by digorithm

When the returned data from a contract call is larger than a word,
it isn't stored in `Return.val`, but in `ReturnData.data`.

Before the changes in here, we were pulling the data only from
`Return.val`, which fortunately handled most cases. Until now,
with some methods returning, for instance, a `b256`, which would cause
the data to _not_ be in `Return.val` as we expected, leading to errors.

This PR introduces some changes to fix this by looking whether the
expected return type is larger than a word, if it is, we fetch the
returned data from `ReturnData.data` instead of `Return.val`.

2022-02-24 22:58 UTC, digorithm commented
@nfurfaro tagging you in this PR because it fixes the issue you found and includes the test cases you used to find the problem. These test cases are now part of the test suite for the SDK.

2022-02-25 00:15 UTC, nfurfaro approved these changes
LGTM!

2022-02-25 16:16 UTC, vnepveu requested changes
Nitpicks

2022-02-25 16:16 UTC, vnepveu commented on fuels-core/src/lib.rs
> +            Self::String(size) => {
`return (size > 8)`

2022-02-25 16:16 UTC, vnepveu commented on fuels-abigen-macro/tests/test_projects/large-return-data/abi.json
> +[{"inputs":[{"components":null,"name":"gas","type":"u64"},{"components":null,"name":"coin","type":"u64"},{"components":null,"name":"color","type":"b256"},{"components":null,"name":"value","type":"()"
I think we usually format on multiple lines

2022-02-25 16:26 UTC, vnepveu approved these changes

2022-02-25 17:19 UTC, merged