feat: log/error on mismatch of client version and supported version
FuelLabs/fuels-rs pull request #1166
Opened 2023-10-12 18:34 UTC by Br1ght0ne

Close https://github.com/FuelLabs/fuels-rs/issues/1138. Shamelessly ported from `fuels-ts`'s https://github.com/FuelLabs/fuels-ts/pull/1287.

### Checklist
- [x] I have linked to any relevant issues.
- [ ] I have updated the documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary labels.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

2023-10-13 10:29 UTC, hal3e requested changes
Looks good. Just have a request regarding visibility

2023-10-13 10:29 UTC, hal3e commented on packages/fuels-accounts/src/lib.rs
> +pub mod supported_versions;
IMO we should not expose this outside of the crate.
```suggestion
mod supported_versions;
```

2023-10-13 10:29 UTC, hal3e commented on packages/fuels-accounts/src/supported_versions.rs
> +pub fn get_supported_fuel_core_version() -> Version {
```suggestion
fn get_supported_fuel_core_version() -> Version {
```

2023-10-13 10:29 UTC, hal3e commented on packages/fuels-accounts/src/supported_versions.rs
> +}
```suggestion
#[derive(Debug, PartialEq, Eq)]
pub(crate) struct VersionCompatibility {
    pub(crate) supported_version: Version,
    pub(crate) is_major_supported: bool,
    pub(crate) is_minor_supported: bool,
    pub(crate) is_patch_supported: bool,
}
```

2023-10-13 10:29 UTC, hal3e commented on packages/fuels-accounts/src/supported_versions.rs
> +pub fn check_fuel_core_version_compatibility(network_version: &Version) -> VersionCompatibility {
```suggestion
pub(crate) fn check_fuel_core_version_compatibility(network_version: &Version) -> VersionCompatibility {
```

2023-10-13 12:42 UTC, iqdecay approved these changes
LGTM, very elegant and quick solution!

2023-10-16 11:18 UTC, MujkicA commented on packages/fuels-accounts/src/supported_versions.rs
> +    actual_version: &Version,
If we accept owned values here, we can move the bellow call to clone() mora towards the edge of our API. I.e. we clone when passing arguments to
`check_fuel_core_version_compatibility`

2023-10-16 14:09 UTC, MujkicA approved these changes
:shipit:

2023-10-16 15:27 UTC, hal3e approved these changes
:rocket:

2023-10-16 15:27 UTC, merged