chore: add test for compute_calls_instructions_len
FuelLabs/fuels-rs pull request #1183
Opened 2023-11-01 14:12 UTC by Br1ght0ne

Close #1129.

### Checklist
- [x] I have linked to any relevant issues.
- [ ] I have updated the documentation.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary labels.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

2023-11-01 15:08 UTC, Br1ght0ne commented
@iqdecay Thank you for the pointers - will do.

2023-11-08 11:08 UTC, MujkicA submitted a review, later dismissed
LGTM

2023-11-08 11:35 UTC, digorithm requested changes
LGTM -- just a minor documentation-related nit.

2023-11-08 11:35 UTC, digorithm commented on packages/fuels-programs/src/call_utils.rs
> +                Instruction::SIZE * (BASE_INSTRUCTION_COUNT + 2)
We should use this opportunity to have these tests act as documentation for the inner workings of the SDK/client. Why `+ 2` here and `+ 4` down there? We should have this info as comments right here.

2023-11-08 15:28 UTC, Br1ght0ne commented on packages/fuels-programs/src/call_utils.rs
> +                    ParamType::Vector(Box::new(ParamType::B256)),
Thank you so much for pointing out the test cases!

2023-12-07 09:00 UTC, hal3e reviewed
This looks very good. Left some small suggestions.

2023-12-13 11:18 UTC, MujkicA approved these changes
Nice

2023-12-13 11:21 UTC, hal3e approved these changes
Thanks!

2023-12-15 15:06 UTC, merged