Support `Upload` and `Upgrade` transactions
FuelLabs/fuels-rs pull request #1382
Opened 2024-05-16 16:45 UTC by xgreenx

### Checklist
- [ ] I have linked to any relevant issues.
- [ ] I have updated the documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary labels.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

2024-05-21 16:52 UTC, segfault-magnet reviewed
We need to add `UploadSubsection` and `UpgradePurpose` somewhere inside `fuels::...` reexports.

a `pub use` in `transaction_builders` is going to propagate it into the `fuels::prelude` and have it be available under `fuels::types::transaction_builders::...`

Also we should add e2e tests to verify that this works, if that's possible @xgreenx ?

2024-05-23 21:25 UTC, xgreenx commented
@segfault-magnet May I ask you to make this PR fulfill your standards of the codebase, please?=)

The example of how I used `Upload` and `Upgrade` transactions you can find in [this](https://github.com/FuelLabs/fuel-utils/blob/master/network-upgrader/src/main.rs#L136) repository.

2024-05-23 22:38 UTC, segfault-magnet commented
> @segfault-magnet May I ask you to make this PR fulfill your standards of the codebase, please?=)
> 
> The example of how I used `Upload` and `Upgrade` transactions you can find in [this](https://github.com/FuelLabs/fuel-utils/blob/master/network-upgrader/src/main.rs#L136) repository.
> 

Sure. Tnx for the PR and the examples, I'll finish it up.

2024-05-28 16:26 UTC, MujkicA approved these changes

2024-05-28 17:11 UTC, digorithm requested changes
Just the tiniest typo. Other than that, it looks great!

2024-05-28 17:11 UTC, digorithm commented on packages/fuels-core/src/types/transaction_builders.rs
> +            .expect("Impossible to fail unless it not enough memory");
```suggestion
            .expect("Impossible to fail unless there is not enough memory");
```

2024-05-30 08:52 UTC, hal3e approved these changes

2024-05-30 08:57 UTC, Salka1988 approved these changes

2024-05-30 10:29 UTC, merged