feat!: Fix gas and fee estimation
FuelLabs/fuels-rs pull request #1396
Opened 2024-05-30 18:36 UTC by MujkicA

### Checklist
- [ ] I have linked to any relevant issues.
- [ ] I have updated the documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary labels.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

2024-06-17 08:15 UTC, Br1ght0ne submitted a review, later dismissed

2024-06-18 10:00 UTC, hal3e requested changes
Looks very good. Have left some nits

2024-06-18 10:00 UTC, hal3e commented on examples/cookbook/src/lib.rs
> +        dbg!(&tx);
```suggestion
```

2024-06-18 10:00 UTC, hal3e commented on packages/fuels-core/src/types/transaction_builders.rs
> +                // TODO: ADD THIS TO DOCS
can you please create an issue for this?

2024-06-18 10:01 UTC, hal3e commented
can you please add the `BREAKING CHANGE` section in the PR description.

2024-06-19 10:03 UTC, hal3e approved these changes
awesome work! thanks

2024-06-19 13:25 UTC, Br1ght0ne approved these changes

2024-06-20 20:02 UTC, digorithm approved these changes

2024-06-20 20:02 UTC, merged