Actually forward gas on contract call
FuelLabs/fuels-rs pull request #386
Opened 2022-06-12 12:05 UTC by MujkicA

Closes #184

This PR adds the field `gas_limit` to `CallParameters`. `gas_limit` is forwarded to the `CALL` instruction when generating the script for performing a contract call.
The difference between transaction gas limit and call gas limit is that the former applies to costs of the whole transaction while the latter specifies what portion of the transaction cost can be spent on the actual call.

Here is an example where we set a call gas limit of 1000
```rust

let call_params = CallParameters::new(None, None, Some(1000));

let result = contract_instance
        .initialize_counter(42)
        .call_params(CallParameters::new(call_params))
        .call()
        .await
        .expect_err("should error");

```

I've also added a test that checks if errors are reported correctly when setting transaction/call gas limits.

2022-06-12 13:29 UTC, Salka1988 approved these changes

2022-06-13 12:44 UTC, segfault-magnet submitted a review, later dismissed

2022-06-13 22:02 UTC, vnepveu requested changes
Some changes needed, thanks for fixing such a longstanding issue!

2022-06-13 22:13 UTC, adlerjohn commented on docs/src/getting-started/basics.md
>  pub const NATIVE_ASSET_ID: AssetId = AssetId::new([0u8; 32]);
Yes, changed in #384. All the more reason to include code instead of writing it inline!

2022-06-15 13:56 UTC, MujkicA commented on packages/fuels-contract/src/script.rs
> +                    segment_offset + AssetId::LEN + 2 * WORD_SIZE + ContractId::LEN + 2 * WORD_SIZE;
The length of each parameter stored in data is in the docstring, I'll just write that we are getting an offset after those values

2022-06-15 17:21 UTC, MujkicA commented on docs/src/getting-started/basics.md
> +        .unwrap();
How can `CallResponse<D>` with a generic be added to the test function signature as output? I can't find any examples of this in code.

2022-06-15 17:22 UTC, MujkicA commented on docs/src/getting-started/basics.md
>  pub const NATIVE_ASSET_ID: AssetId = AssetId::new([0u8; 32]);
What would be the best way to include this since its outside of our examples?

2022-06-15 17:47 UTC, vnepveu commented on docs/src/getting-started/basics.md
>  pub const NATIVE_ASSET_ID: AssetId = AssetId::new([0u8; 32]);
you can just add the `ANCHOR: xxx` tag as you would for code exemple then include the file. Just rebase/merge master, I included this already in my work on  docs migration.

2022-06-15 17:48 UTC, vnepveu commented on docs/src/getting-started/basics.md
> +        .unwrap();
Don't return this as an output, basically use `Result<(), Error>` as function return, and end your test function with `Ok(())`

2022-06-15 22:14 UTC, adlerjohn reviewed
Avoid manual line breaks for markdown text.

2022-06-15 22:14 UTC, adlerjohn commented on docs/src/getting-started/basics.md
> +available gas will be forwarded.
```suggestion
The `gas_limit` parameter differs from the one in `TxParameters` in that it defines the limit for the actual contract call as opposed to the gas limit for the whole transaction. This means that it is constrained by the transaction limit. If it is set to an amount grater than the available gas, all available gas will be forwarded.
```

2022-06-15 22:14 UTC, adlerjohn commented on docs/src/getting-started/basics.md
> +while the actual call may only consume up to 200 gas:
```suggestion
Here we use both the transaction and call `gas_limit` to specify that the contract call transaction may consume up to 1000 gas while the actual call may only consume up to 200 gas:
```

2022-06-15 22:14 UTC, adlerjohn commented on packages/fuels-abigen-macro/tests/test_projects/msg_amount/Cargo.toml
> +authors = ["hamdija"]
```suggestion
authors = ["Fuel Labs <contact@fuel.sh>"]
```

2022-06-15 22:14 UTC, adlerjohn commented on packages/fuels-abigen-macro/tests/test_projects/msg_amount/Forc.toml
> +authors = ["hamdija"]
```suggestion
authors = ["Fuel Labs <contact@fuel.sh>"]
```

2022-06-15 22:14 UTC, adlerjohn commented on packages/fuels-contract/src/script.rs
> +    /// 0x11 Gas price
?
```suggestion
    /// 0x11 Gas limit
```

2022-06-15 22:31 UTC, vnepveu approved these changes
lgtm

2022-06-15 22:58 UTC, adlerjohn reviewed
Looks good to me, will defer to @vnepveu or @digorithm for final review. Good work!

2022-06-15 23:20 UTC, digorithm requested changes
LGTM, great stuff! Hopefully the tx's `gas_limit` and call's `gas_limit` won't be confusing to the users 🤔. 

Found just a small typo; feel free to merge after!

2022-06-15 23:20 UTC, digorithm commented on docs/src/getting-started/basics.md
> +The `gas_limit` parameter differs from the one in `TxParameters` in that it defines the limit for the actual contract call as opposed to the gas limit for the whole transaction. This means that it is
```suggestion
The `gas_limit` parameter differs from the one in `TxParameters` in that it defines the limit for the actual contract call as opposed to the gas limit for the whole transaction. This means that it is constrained by the transaction limit. If it is set to an amount greater than the available gas, all available gas will be forwarded.
```

2022-06-15 23:30 UTC, adlerjohn commented
> Hopefully the tx's gas_limit and call's gas_limit won't be confusing to the users 🤔.

I went back and forth on this and decided against commenting it, but then @digorithm brought it up so here goes: can @MujkicA can you file an issue to follow-up on this PR to change the call gas limit to something like "gas forwarded"? Semantically, a transaction has a limit to how much gas it can use, but isn't _forwarded_ any gas. When contract calls are made, gas is actually sent (forwarded) with the call.

2022-06-15 23:34 UTC, digorithm commented
> > Hopefully the tx's gas_limit and call's gas_limit won't be confusing to the users 🤔.
> 
> I went back and forth on this and decided against commenting it, but then @digorithm brought it up so here goes: can @MujkicA can you file an issue to follow-up on this PR to change the call gas limit to something like "gas forwarded"? Semantically, a transaction has a limit to how much gas it can use, but isn't _forwarded_ any gas. When contract calls are made, gas is actually sent (forwarded) with the call.

Haha sorry for the troubles @MujkicA; after reading the docs I felt a bit confused about the terminology, but after re-reading and reading some code it made sense, but there was some friction. So I'm guessing that could happen with the users as well. 

I like John's suggestion here, but as he said, can leave it for a follow-up PR.

2022-06-15 23:36 UTC, MujkicA commented
No problem at all. I'd rather change it in this PR if that is ok.

2022-06-16 00:14 UTC, digorithm approved these changes
Yup, that change in the naming made things much clearer. LGTM!

2022-06-16 00:14 UTC, merged

2022-06-16 00:16 UTC, digorithm commented
Damn, this `enabled auto-merge (squash)` thingy is scary; for a second I thought I pressed the merge button 😂.