Encoding of an enum with all unit variants (#390)
FuelLabs/fuels-rs pull request #409
Opened 2022-06-17 17:04 UTC by segfault-magnet

### The issue
The sway compiler, since the release of Forc 16.0.0, includes an optimization with regards to enums that only have unit types for variants.

Such enums are to be encoded in only one word that contains their discriminant.

This PR also contains the necessary fixes to our Sway files thanks to @digorithm 

### The solution 
The cleanest way of looking at this is to say that enums with only unit variants will not have their unit variant encoded at all. This is preferable to wording like 'units are 0B in enums, 1 B elsewhere'. Although the 'elsewhere' part can be debated since the SDK doesn't support using Units anywhere else. This phrasing was translated into code.

Although the changes are covered by unit tests, there is an e2e test that will safeguard us against regressions in the sway compiler -- the test will only pass if the aforementioned type of enums is encoded in one word.

I've also taken the liberty of refactoring ABIEncoder, since it was unnecessarily storing the encoded function selector while it was only necessary for it to compute it.

The flow of 'construct an encoder, give it data, get the encoding back' was wrapped in an associated function which can now be called `ABIEncoder::encode(...)` since this is the only way the encoder is used.

2022-06-17 18:58 UTC, adlerjohn reviewed
CI failing

2022-06-18 21:25 UTC, digorithm requested changes
Tiny nits, other than that LGTM. Nice refactor and test 🔥

2022-06-18 21:25 UTC, digorithm commented on packages/fuels-core/src/abi_encoder.rs
> +    /// [here](https://github.com/FuelLabs/fuel-specs/blob/master/specs/protocol/abi.md)
Do you mind using the permalink here? i.e. https://github.com/FuelLabs/fuel-specs/blob/1be31f70c757d8390f74b9e1b3beb096620553eb/specs/protocol/abi.md

2022-06-20 09:08 UTC, Br1ght0ne submitted a review, later dismissed
Other than what @digorithm said, LGTM 🎉

2022-06-20 14:25 UTC, digorithm approved these changes
:shipit:

2022-06-20 14:25 UTC, merged