add features.md and fuel-core lib doc.
FuelLabs/fuels-rs pull request #480
Opened 2022-07-18 08:42 UTC by Salka1988

2022-07-18 09:46 UTC, vnepveu requested changes
This is going in the right direction, but IMO you should be documenting how to use the feature (people unfamiliar would not necessarily know how to). Also I think you could put it inside the `Running a short-lived fuel-node` as a paragraph, I think it would make more sense, what do you think? Since it's used for connecting to a node in that case.

2022-07-18 09:46 UTC, vnepveu commented on docs/src/providers/features.md
> +The `fuel-core-lib` feature allows us to run a fuel-core node without installing the fuel-core binary on the local machine. This entails downloading all the dependencies needed to run the fuel-core n
You should explain what dependencies it requires, maybe even put an example `Cargo.toml` file like in the `Setup` part.

2022-07-18 23:45 UTC, digorithm requested changes

2022-07-18 23:45 UTC, digorithm commented on docs/src/providers/short-lived.md
> +### Fuel-core lib
```suggestion
## Fuel-core lib
```

2022-07-18 23:45 UTC, digorithm commented on docs/src/providers/short-lived.md
> +The `fuel-core-lib` is a feature defined in `fuels` library, and it allows us to run a fuel-core node without installing the fuel-core binary on the local machine. This entails downloading all the de
Clarity improvements:

```suggestion
The `fuel-core-lib` is a feature defined in the `fuels` library, allowing us to run a `fuel-core` node without installing the `fuel-core` binary on the local machine. Using the `fuel-core-lib` feature flag entails downloading all the dependencies needed to run the fuel-core node.
```

2022-07-19 12:14 UTC, vnepveu approved these changes
perfect! will be clearer for future users :1st_place_medal:

2022-07-19 14:49 UTC, digorithm approved these changes
:shipit:

2022-07-19 15:43 UTC, merged