feat: add predicate example and docs
FuelLabs/fuels-rs pull request #541
Opened 2022-08-25 16:32 UTC by hal3e

closes: https://github.com/FuelLabs/fuels-rs/issues/535

I have added a simple predicate example which requires the user to send two out of three signatures that match some hard coded public keys.

2022-08-25 16:59 UTC, Br1ght0ne requested changes
Other than a few typos, looks wonderful.

2022-08-25 16:59 UTC, Br1ght0ne commented on docs/src/getting-started/predicates.md
> +Predicates, in Sway, are programs that return a Bolean value and they do not have any side effects (they are pure).
```suggestion
Predicates, in Sway, are programs that return a Boolean value and they do not have any side effects (they are pure).
```

2022-08-25 16:59 UTC, Br1ght0ne commented on docs/src/getting-started/predicates.md
> +Similarity to contracts, once you've written a predicate in Sway and compiled it with `forc build` (read [here](https://fuellabs.github.io/sway/master/introduction/overview.html) for more on how to w
```suggestion
Similarly to contracts, once you've written a predicate in Sway and compiled it with `forc build` (read [here](https://fuellabs.github.io/sway/master/introduction/overview.html) for more on how to work with Sway), you'll get the predicate binary. Using the binary, you can instantiate an `predicate` as shown in the code snippet below:
```

2022-08-25 17:21 UTC, MujkicA reviewed
Just a couple of nits, maybe we could/should mention that signing over an array of zeroes is just for the sake of the example. 
Great example btw!

2022-08-25 17:21 UTC, MujkicA commented on docs/src/getting-started/predicates.md
> +In the next section, we will show in detail how to interact with a predicate and explore an example where specific signatures are needed to spend the predicate funds.
Personal preference, take it or leave it
```suggestion
In the next section, we show how to interact with a predicate and explore an example where specific signatures are needed to spend the predicate funds.
```

2022-08-25 17:21 UTC, MujkicA commented on docs/src/getting-started/predicates.md
> +Predicates, in Sway, are programs that return a Bolean value and they do not have any side effects (they are pure).
```suggestion
Predicates, in Sway, are programs that return a Boolean value, and they do not have any side effects (they are pure).
```

2022-08-25 17:21 UTC, MujkicA commented on docs/src/getting-started/predicates.md
> +Similarity to contracts, once you've written a predicate in Sway and compiled it with `forc build` (read [here](https://fuellabs.github.io/sway/master/introduction/overview.html) for more on how to w
```suggestion
Similar to contracts, once you've written a predicate in Sway and compiled it with `forc build` (read [here](https://fuellabs.github.io/sway/master/introduction/overview.html) for more on how to work with Sway), you'll get the predicate binary. Using the binary, you can instantiate a `predicate` as shown in the code snippet below:
```

2022-08-25 17:21 UTC, MujkicA commented on docs/src/getting-started/predicates.md
> +The created `predicate` instance has two fields. The predicate `byte code` and the predicate `address`. This address is generated from the byte code and is the same as the `P2SH` address used in Bitc
```suggestion
The created `predicate` instance has two fields. The predicate `byte code` and the predicate `address`. This address is generated from the byte code and is the same as the `P2SH` address used in Bitcoin. Users can seamlessly send assets to the predicate address as they do for any other address on the chain. To spend the predicate funds, the user has to provide the original `byte code` of the predicate together with the `predicate data`. The `predicate data` will be used when executing the `byte code`, and if the predicate is validated successfully, the funds will be accessible.
```

2022-08-25 17:21 UTC, MujkicA commented on docs/src/predicates/send-spend-predicate.md
> +This predicate accepts three signatures and matches them to three predefined public keys. The `ec_recover_address` function is used to recover the public key from the signatures. If two of three extr
```suggestion
This predicate accepts three signatures and matches them to three predefined public keys. The `ec_recover_address` function is used to recover the public key from the signatures. If two of three extracted public keys match the predefined public keys, the funds can be spent. Note that the signature order has to match the order of the predefined public keys.
```

2022-08-25 17:21 UTC, MujkicA commented on docs/src/predicates/send-spend-predicate.md
> +After the predicate address is generated we can send funds to it. Note that we are using the same `tranfer` function as we used when sending funds to other wallets. We also make sure that the funds a
```suggestion
After the predicate address is generated we can send funds to it. Note that we are using the same `transfer` function as we used when sending funds to other wallets. We also make sure that the funds are indeed transferred.
```

2022-08-25 17:21 UTC, MujkicA commented on docs/src/predicates/send-spend-predicate.md
> +To spend the funds that are now locked in the predicate we have to provide two out of three signatures whose public keys match the ones we defined in the predicate. The signatures are generate in the
```suggestion
To spend the funds that are now locked in the predicate we have to provide two out of three signatures whose public keys match the ones we defined in the predicate. The signatures are generated in the snippet below:
```

2022-08-25 17:21 UTC, MujkicA commented on docs/src/predicates/send-spend-predicate.md
> +After generating the signatures, we can actually send a transaction to spend the predicate funds. We use the `receiver` wallet as the recipient. In the transaction we have to provide both the predica
Typo + personal preference
```suggestion
After generating the signatures, we can send a transaction to spend the predicate funds. We use the `receiver` wallet as the recipient. We have to provide the predicate byte code and the required signatures. As we provide the correct data, we receive the funds and verify that the amount is correct.
```

2022-08-26 11:54 UTC, segfault-magnet approved these changes

2022-08-26 11:54 UTC, segfault-magnet commented on examples/predicates/src/lib.rs
> +        let secret_key1: SecretKey =
A fun helper:
```rust
    fn wallets_from_keys<const T: usize>(keys: &[&str; T]) -> [LocalWallet; T] {
        keys.map(|hash| LocalWallet::new_from_private_key(hash.parse().unwrap(), None))
    }
    // ... later on
        let [wallet, wallet2, wallet3] = wallets_from_keys(&[
            "0x862512a2363db2b3a375c0d4bbbd27172180d89f23f2e259bac850ab02619301",
            "0x37fa81c84ccd547c30c176b118d5cb892bdb113e8e80141f266519422ef9eefd",
            "0x976e5c3fa620092c718d852ca703b6da9e3075b9f2ecb8ed42d9f746bf26aafb",
        ]);

```

2022-08-26 11:54 UTC, segfault-magnet commented on examples/predicates/src/lib.rs
> +        let secret_key1: SecretKey =
Albeit only now do I see the anchors. We probably keep things 'vanilla' here :) 

But I'll leave the comment be :) Might be useful in the future.

2022-08-29 09:51 UTC, MujkicA approved these changes
LGTM

2022-08-29 10:03 UTC, Br1ght0ne approved these changes
LGTM!

2022-08-29 14:09 UTC, digorithm approved these changes

2022-08-29 14:12 UTC, merged