fix: field `time` in `Header` and `TransactionResponse`
FuelLabs/fuels-rs pull request #739
Opened 2022-12-10 06:51 UTC by cheng404

Hello, I found out a bug about the `time` field in `client.query` results.

the `time` value of the following code is always `None` 

### 1. transaction response
```
let tx_id = "0x7e46c2447d3788be0a41550edaebed99fe6b28c60d1c01186fc0d70d72c38a68";
let provider = Provider::connect("node-beta-2.fuel.network").await.unwrap();
let tx = provider.get_transaction_by_id(tx_id).await.unwrap();
println!("{:#?}", tx);
```

### 2. block header
```
let block_id = "0xba4f5c3197f72f752b82cc46c170b550f5ac6e320656683b2693af0b748d5dd4";
let provider = Provider::connect("node-beta-2.fuel.network").await.unwrap();
let block = provider.block(block_id).await.unwrap();
println!("{:#?}", block);
```

### Fix

use `to_unix()` to convert `TAI64` to timestamp

2022-12-10 09:22 UTC, MujkicA submitted a review, later dismissed
Good catch. Thank you for contributing!
Left a small formatting fix for the CI to pass.

2022-12-10 09:22 UTC, MujkicA commented on packages/fuels-types/src/block.rs
> +        let naive = NaiveDateTime::from_timestamp_opt(client_header.time.0 .to_unix(), 0);
```suggestion
        let naive = NaiveDateTime::from_timestamp_opt(client_header.time.0.to_unix(), 0);
```

2022-12-15 21:13 UTC, iqdecay requested changes
Thank you! This is good, but it's better if you can add a test that shows that the bug you experienced before is no longer here. Lmk if you need help writing the test :smile:

2022-12-17 05:40 UTC, cheng404 commented
time parameter of `produce_blocks` should be `TAI64 ` format
https://github.com/FuelLabs/fuels-rs/blob/fce0631cf8778a04d70cf8fdffa0d207b211c4b9/packages/fuels-signers/src/provider.rs#L414

I noticed that there are some changes in `fuel-core` structure of project, so adding 'tai64' dependence is a kind of temporary solution and I will follow up on the changes.

2022-12-22 19:46 UTC, digorithm commented
@cheng404 Do you mind syncing this branch with master?

2022-12-23 03:17 UTC, cheng404 commented
> 
Done. :)

2023-01-02 11:19 UTC, MujkicA approved these changes
LGTM!
Once again, thanks for contributing.

2023-01-07 12:17 UTC, iqdecay approved these changes
nice, thanks for your contribution! @cheng404 I'm letting you the pleasure of clicking the green "Merge" button :smile:

2023-01-07 18:14 UTC, cheng404 commented
> nice, thanks for your contribution! @cheng404 I'm letting you the pleasure of clicking the green "Merge" button 😄
It's my pleasure. I have no `write access` to this repository, and can't merge and close PR

2023-01-07 18:31 UTC, merged

2023-01-07 18:32 UTC, iqdecay commented
> It's my pleasure. I have no `write access` to this repository, and can't merge and close PR
Woops I didn't know that haha. Merged! :tada: