Expand inputs and avoid duplicates
FuelLabs/fuels-rs pull request #764
Opened 2023-01-04 16:12 UTC by Salka1988

closes #758

```rust 
pub struct PrepareExecutableFuelCall {
    pub(crate) tx: fuels_core::tx::Script,
    pub(crate) calls: Calls,
    pub(crate) wallet: WalletUnlocked,
    pub(crate) inputs: Vec<Input>,
    pub(crate) outputs: Vec<Output>,
}
```
The `from_contract_calls` function enables us to convert a `ContractCall` into an executable call. We can add `inputs` and `outputs` without worrying about duplicates, as the `prepare` function will be called afterwards to collect all entries and perform the necessary checks for execution. The resulting `ExecutableFuelCall` structure should not be modified unless we are confident in our actions.

2023-01-05 14:01 UTC, MujkicA reviewed
I think this doesn't remove the original issue. Seems to me like the only options we have is to relinquish full responsibility for adding enough resources to cover fees to the user if they choose to modify inputs or only allow them to add certain amount/asset combinations without specifying the messages/coins that should constitute the inputs.

2023-01-08 11:48 UTC, iqdecay requested changes
I'm not a big fan of the UX, and also agree with what Ahmed said.

2023-01-08 11:48 UTC, iqdecay commented on examples/cookbook/src/lib.rs
> +        let mut executable_call = call_handler.get_executable_call().await?.prepare().await?;
I don't like the UX of this, it is yet another chain of `method()` to just do a contract call.
From what I understand, the suggestion was to let the user do her thing, and then only do one pass for requesting resources (both for fees and resources) from the node.

2023-01-08 11:48 UTC, iqdecay commented on packages/fuels-contract/src/contract_calls_utils.rs
> -    fn contract_input_present() {
same question

2023-01-10 22:05 UTC, Salka1988 commented on packages/fuels-contract/src/contract_calls_utils.rs
> -    fn contract_input_present() {
these were the tests for the feature I deleted in this branch

2023-01-11 12:51 UTC, Salka1988 commented
After further discussion and consideration, we have decided to take a different approach to solving the problem, which you can be found on branch #778

2023-01-11 12:51 UTC, closed without merging