Bump CI forc to 0.33
FuelLabs/fuels-rs pull request #782
Opened 2023-01-17 15:30 UTC by MujkicA

2023-01-17 15:31 UTC, mohammadfawaz submitted a review, later dismissed

2023-01-18 16:37 UTC, segfault-magnet requested changes
Something fun is happening with the projects. Sway build is failing.

2023-01-18 16:40 UTC, segfault-magnet commented
> Something fun is happening with the projects. Sway build is failing.

@MujkicA do you mind, after fixing the issue, to bump to 0.33.1 due to [this](https://fuellabs.slack.com/archives/C02RU9MNVKN/p1674059496703849?thread_ts=1674059202.655099&cid=C02RU9MNVKN)?

2023-01-18 20:06 UTC, digorithm approved these changes

2023-01-18 21:14 UTC, merged