docs: update node-beta-1 to node-beta-2
FuelLabs/fuels-rs pull request #797
Opened 2023-01-25 10:02 UTC by Salka1988

Update the `Connecting to the Testnet or an external node` section to refer to beta-2 instead of beta-1

closes #773

2023-01-25 13:20 UTC, hal3e requested changes
We have to also update the documentation.

Specifically, the faucet info on this page:
https://fuellabs.github.io/fuels-rs/v0.34.0/providers/external-node.html

Also the `Testnet` link on this page is not working:
https://fuellabs.github.io/fuels-rs/v0.34.0/index.html

2023-01-25 21:19 UTC, iqdecay approved these changes

2023-01-25 21:28 UTC, digorithm approved these changes
Note that within a few days, we'll have to update it to `node-beta-3` 😂

2023-01-26 08:31 UTC, hal3e approved these changes

2023-01-26 08:46 UTC, merged