chore: reorganize harness tests
FuelLabs/fuels-rs pull request #897
Opened 2023-03-20 14:38 UTC by hal3e

closes: https://github.com/FuelLabs/fuels-rs/issues/896

In this PR I propose a new harness tests layout for types in our SDK. The main idea is to separate types test based on the program. Initially, we agreed on `contracts` and `scripts` but I have also separated `predicates`. This is the new structure:

```shell
tests
...
│
├── types/
│  ├── contracts/
│  │  ├── b512/
│  │  ...
│  │  ├── vector_output/
│  │  └── vectors/
│  ├── predicates/
│  │  ├── address/
│  │  ...
│  │  ├── structs/
│  │  └── u64/
│  └── scripts/
│     ├── options_results/
│  │  ...
│     ├── script_vector/
│     └── script_vectors/
 ...
├── types_contracts.rs
├── types_predicates.rs
└── types_scripts.rs
...
```
Changes:
- `types` folder has 3 subfolder for each program
- `types.rs` was split into three files `types_contracts.rs`, `types_predicates.rs` and `types_scripts.rs`type_safe_output_values
- Removed program name from sway project where they were not needed. E.g.  `contract_storage_test` -> `storage`
- Deleted duplicated test: `type_safe_output_values`
- Deleted unused sway projects: `require_contract_abi` `require_from_contract`

### Checklist
- [x] I have linked to any relevant issues.
- [x] I have updated the documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary labels.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

2023-03-21 15:42 UTC, iqdecay requested changes
Just one question

2023-03-21 15:42 UTC, iqdecay commented on packages/fuels/tests/types_contracts.rs
> -async fn type_safe_output_values() -> Result<()> {
This was deleted because it is redundant?

2023-03-21 22:08 UTC, iqdecay commented
I think we hold off merging until #815 is merged?

2023-03-22 07:45 UTC, hal3e commented
> I think we hold off merging until #815 is merged?

Makes sense. That PR is done. We just need to merge it.

2023-03-23 00:34 UTC, iqdecay submitted a review, later dismissed
noice

2023-03-23 16:36 UTC, iqdecay approved these changes

2023-03-23 20:25 UTC, digorithm approved these changes
Nice -- clean re-organization!

2023-03-23 20:43 UTC, merged