feat: `low level call`support
FuelLabs/fuels-rs pull request #958
Opened 2023-05-09 18:59 UTC by Salka1988

This PR adds two macros to the project: `fn_selector!()` and `calldata()`.
These macros simplify the usage of the `std::low_level_call::call_with_function_selector` function by providing a more convenient way to generate the function_selector and calldata arguments.

contracts/low_level_call/src/main.sw
```sw
fn call_low_level_call(
    target: ContractId,
    function_selector: Bytes,
    calldata: Bytes,
    single_value_type_arg: bool,
) {
    let call_params = CallParams {
        coins: 0,
        asset_id: BASE_ASSET_ID,
        gas: 10_000,
    };

    call_with_function_selector(target, function_selector, calldata, single_value_type_arg, call_params);
}
```
low_level_cal test
```rust
let function_selector = fn_selector!(set_value(u64));
let call_data = calldata!(42u64);

contract_instance
    .methods()
    .call_low_level_call(
        contract_id.clone().into(),
        Bytes(function_selector),
        Bytes(call_data),
        true,
    )
    .call()
    .await?;
```

### Checklist
- [x] I have linked to any relevant issues.
- [ ] I have updated the documentation.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary labels.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

2023-05-09 19:10 UTC, Salka1988 commented
I faced a challenge while attempting to enable `return` for `call_with_function_selector` function for dynamic data types. `Vec<_>`
I sought the opinion of @MujkicA  and together we concluded that returning `Vec<>` would not be feasible without support from the SWAY team. @nfurfaro later confirmed that supporting `low_level_call return` may not be necessary at all. In light of this, I decided to remove support for returning static data for the time being, with the possibility of adding it later if required.

2023-05-09 21:55 UTC, nfurfaro reviewed
This looks good. As you mentioned, a future enhancement could be to handle dynamic return data if needed.
One other thing that could be good to check here would be to deploy a second contract "Target" which has all the abi functions currently in the test contract except for the low_level_call function.
The idea would be to call `Contract_A.low_level_call`, passing the `ContractId` of the Target contract, the function selector and call params.
Everything should continue to work the same, but that's more representative of how this will be used. The key difference here being that we don't need to use the abigen! macro for the target contract; we just need its `ContractId` and a function selector.

2023-05-10 16:45 UTC, nfurfaro approved these changes
Looks good to me!

2023-05-17 16:06 UTC, MujkicA commented on packages/fuels/tests/contracts.rs
> +    assert_eq!(response.value, 42);
I would move this assertion to the test in `/examples` and have this test focused on `set_value_multiple_complex`

2023-05-18 11:36 UTC, MujkicA approved these changes

2023-05-19 01:15 UTC, iqdecay requested changes
Can you just please add unit tests that showcase what the generated code looks like

2023-05-19 01:15 UTC, iqdecay commented on packages/fuels-core/src/function_selector.rs
> +pub use calldata;
Can we add some basic unit tests for those macros?

2023-05-22 18:19 UTC, iqdecay approved these changes
lgtm

2023-05-22 19:03 UTC, merged