chore: re-export more fuel-tx
FuelLabs/fuels-rs pull request #969
Opened 2023-05-16 21:25 UTC by ra0x3

### Checklist
- [x] I have linked to any relevant issues.
- [x] I have updated the documentation.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary labels.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

### Description
- Re-exporting more of `fuel-tx` so that we don't have to use `fuel-tx` directly. 
- This will obviously break when upgrading to `fuel-tx 0.31` but cross that bridge when we get to it?

2023-05-17 16:45 UTC, ra0x3 commented on packages/fuels/src/lib.rs
> +        Transaction, TxId,
@hal3e 
- Users actually use `Transaction` in their indexers. 
- [Here's an example](https://github.com/FuelLabs/fuel-indexer/blob/master/examples/block-explorer/explorer-indexer/src/lib.rs#L75)
- I'm happy to alias it as something else

2023-05-19 01:38 UTC, iqdecay commented on packages/fuels/src/lib.rs
> +        Transaction, TxId,
Yeah we definitely don't want to export it as `Transaction` IMO. `FuelTxTransaction` or `FuelTransaction` can work IMO. 
Needs #850 either way.

2023-05-19 01:39 UTC, iqdecay requested changes
I also think it needs to be aliased.

2023-05-19 01:39 UTC, iqdecay commented on packages/fuels/src/lib.rs
> +        Transaction, TxId,
```suggestion
    pub use fuel_tx::{
        field, Bytes32, ConsensusParameters, Receipt, Salt, ScriptExecutionResult, StorageSlot,
        Transaction as FuelTransaction, TxId,
```

2023-05-20 11:58 UTC, segfault-magnet approved these changes

2023-05-26 16:38 UTC, iqdecay approved these changes
sorry I didn't approve earlier

2023-05-30 09:23 UTC, Salka1988 approved these changes

2023-06-01 10:08 UTC, hal3e approved these changes
LGTM

2023-06-01 10:08 UTC, merged